listen:
  http_proxy: "127.0.0.1:8080"
  socks5_proxy: "127.0.0.1:1080"
  api: "127.0.0.1:8081"

timeouts:
  dial_ms: 5000
  read_ms: 30000
  write_ms: 30000

tor:
  enabled: false

refresh:
  enable_general_sources: false
  interval_sec: 900
  healthcheck_concurrency: 10
  sources: []

database:
  path: "./test.db"

logging:
  level: "info"
  format: "text"

metrics:
  enabled: true
  path: "/metrics"

admin:
  enabled: true
  bind: "127.0.0.1"
  port: 5001
  basePath: "/admin"
  sessionSecret: ""
  allowCIDRs: ["127.0.0.1/32"]
  tls:
    enabled: false

security:
  passwordHash: "argon2id"
  login:
    maxAttempts: 10
    windowSeconds: 900
